AllCops:
  Exclude:
      - 'db/seeds.rb'
      - 'bin/*'
      - config/initializers/*.rb
      - Gemfile
      - db/schema.rb
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 99
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 40
